name: MSYS2
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop
  schedule:
    - cron:  '30 13 2 2,4,6,8,10,12 *'

jobs:
  msys2-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: xz mingw-w64-x86_64-gcc automake autoconf make git pkgconf mingw-w64-x86_64-gettext gettext-devel mingw-w64-x86_64-openssl libtool mingw-w64-x86_64-gtk3
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/lib3270"
          latest: true
          fileName: "mingw-lib3270.tar.xz"      
      - name: CI-Build
        run: |
          ./win/ci-build.sh
      - name: pack
        run: |
          7z a mingw-libv3270.zip .bin\package\mingw64\*
      - uses: ncipollo/release-action@v1
        with:
          tag: 5.4
          artifacts: "*.zip,*.xz"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true

