name: Publish
on:
  push:
    branches: [ "publish", "windows" ]
    tags: [ "*" ]
  
jobs:
  publish-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/libv3270
          releases-only: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix mingw-w64-x86_64-meson mingw-w64-x86_64-gcc git pkgconf mingw-w64-x86_64-gettext gettext-devel mingw-w64-x86_64-openssl mingw-w64-x86_64-gtk3
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/lib3270"
          latest: true
          fileName: "mingw-w64-x86_64-lib3270-5.5.0-0-x86_64.pkg.tar.zst"
      - name: CI-Build
        run: |
          pacman -U --noconfirm *.pkg.tar.zst
          dos2unix PKGBUILD.mingw
          makepkg BUILDDIR=/tmp/pkg -p PKGBUILD.mingw
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "*v3270*.pkg.tar.zst"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
