name: Publish
on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - master
      - develop      
jobs:
  msys2-mingw:
    name: Publish Windows 64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/libv3270
          sort-tags: true
          releases-only: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix mingw-w64-x86_64-gcc automake autoconf make git pkgconf mingw-w64-x86_64-gettext gettext-devel mingw-w64-x86_64-openssl libtool mingw-w64-x86_64-gtk3
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/lib3270"
          latest: true
          fileName: "mingw-w64-x86_64-lib3270-5.4-0-x86_64.pkg.tar.zst"      
      - name: CI-Build
        run: |
          ./win/ci-build.sh
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "*-libv3270-*.pkg.tar.zst"
          allowUpdates: true
          draft: true
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
  macos:
    name: Publish macos
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/libv3270
          releases-only: true
      - name: Install Pre reqs
        run: |
          brew update
          brew install xz automake binutils coreutils curl gettext libtool openssl pkgconfig gtk+3
          brew upgrade
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "PerryWerneck/lib3270"
          latest: true
          fileName: "macos-lib3270.tar.xz"      
      - name: build
        run: ./mac/ci-build.sh
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "macos-libv3270.tar.xz"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true

